### 1. Получение профиля пользователя
GET http://localhost:3000/profile/2
Accept: application/json

### 2. Получение документов пользователя
GET http://localhost:3000/user-documents/3
Accept: application/json

### 3. Регистрация нового пользователя с генерацией токена
POST http://localhost:3000/registration
Content-Type: application/json

{
  "username": "test_user_token",
  "password": "password123",
  "full_name": "Тестовый Тест Токен",
  "phone": "89991112233"
}

### 4. Добавление документа
POST http://localhost:3000/documents
Content-Type: application/json

{
  "user_id": 3,
  "document_name": "Сертификат участника олимпиады",
  "category_id": 2
}

### 5. Проверка категорий
GET http://localhost:3000/categories
Accept: application/json

### 6. Попытка зайти без прав админа
GET http://localhost:3000/admin/users
Accept: application/json
#  ID обычного пользователя
x-user-id: 2

### 7. Успешный запрос от админа
GET http://localhost:3000/admin/users
Accept: application/json
# ID администратора
x-user-id: 1

### 8. Обновление документа (Одобрение)
PATCH http://localhost:3000/admin/documents/10
Content-Type: application/json
x-user-id: 1

{
  "status": "Одобрено",
  "points": 30
}

### 9. Авторизация администратора
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

### 10. Авторизация обычного пользователя
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "test_user",
  "password": "password123"
}

### 11. Получение списка всех абитуриентов (админ)
GET http://localhost:3000/admin/users
Accept: application/json
x-user-id: 1

### 12. Начисление баллов за документ
PATCH http://localhost:3000/admin/documents/10
Content-Type: application/json
x-user-id: 1

{
  "status": "Одобрено",
  "points": 50
}

### 13. Попытка начисления баллов без прав админа
PATCH http://localhost:3000/admin/documents/10
Content-Type: application/json
x-user-id: 2

{
  "status": "Одобрено",
  "points": 25
}